build: add missing packages in the docker file
there are some missing package
during build time it complains for
error: Failed build dependencies:
        checkpolicy is needed by drbd-9.33.0-1.el8.x86_64
        keyutils-libs-devel is needed by drbd-9.33.0-1.el8.x86_64
        selinux-policy-devel is needed by drbd-9.33.0-1.el8.x86_64

So added them to the build file

Signed-off-by: parth-gr <partharora1010@gmail.com>